/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Materials_Create = require('./code/before-materials-create');
const before_Materials_Update = require('./code/before-materials-update');
const before_Materials_Delete = require('./code/before-materials-delete');
const after_Materials_Read = require('./code/after-materials-read');

class myNamespaceSrv extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'Materials', async (request) => {
            await before_Materials_Create(request);
        });

        this.before('UPDATE', 'Materials', async (request) => {
            await before_Materials_Update(request);
        });

        this.before('DELETE', 'Materials', async (request) => {
            await before_Materials_Delete(request);
        });

        this.after('READ', 'Materials', async (results, request) => {
            await after_Materials_Read(results, request);
        });

        return super.init();
    }
}


module.exports = {
    myNamespaceSrv
};